DROP TABLE IF EXISTS geojson;

CREATE TABLE IF NOT EXISTS geojson (
id SERIAL PRIMARY KEY,
geometry GEOMETRY(MULTILINESTRING,4326),
name TEXT,
type TEXT,
email TEXT
);

CREATE INDEX idx_geojson ON geojson USING GIST(geometry);